[package]
name = "conclave-server-lib"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conclave-room = "0.0.1"
unique-id-collection = "0.1.0"
conclave-types = "0.0.1"
